import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Common/Header";
import Footer from "@/components/Common/Footer";
import MobileBottomTab from "@/components/Common/MobileBottomTab";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body
      className="font-inter"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{backgroundColor: "#255EC8"}}
      >
         <Header />
        {children}
        <MobileBottomTab />
        <Footer />
      </body>
    </html>
  );
}